FROM python:3.8

# Create the working dir
RUN bash -c "mkdir -p /workspace/{eocb,input,output,tmp}"

WORKDIR /workspace

# Install dependencies
COPY ./eocb ./tmp

RUN pip install -r ./tmp/requirements.txt
RUN pip install -r ./tmp/requirements-dev.txt

# Clean up txt files
RUN bash -c "rm -r ./tmp"
