version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    tty: true
    volumes:
      - "./data/input:/eocb/input/"
      - "./data/output:/eocb/output/"
      - "./eocb:/eocb/eocb/"
