version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    tty: true
    volumes:
      - "./data/input:/workspace/input/"
      - "./data/output:/workspace/output/"
      - "./eocb:/workspace/eocb/"
